Feat: Entity 마무리
For-MZ/formz-be pull request #12
Opened 2024-02-27 02:04 UTC by pis03133

## Key Changes 🔑

domain Entity 구현
base Entity 구현
빈 스키마에서 app 실행 시, table 생성되도록 부분 주석 처리

## To Reviewers 🙌🏻

처음 한번 app 실행 시키면 연관관계 때매 에러 한번 뜹니다
재실행하면 table 잘 생겨요

## PR Checklist ✔️

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.

## PR 타입 👏🏻

- [x] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 문서 업데이트
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

2024-02-27 02:35 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/user/entity/User.java
> +    private Role role;
@Enumrated EnumType.STRING 사용하시는거 어떻게 생각하시나요??

2024-02-27 03:07 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/profile/entity/Profile.java
프로필 도메인은 ERD 상에는 존재하지 않는 것 같은데, 어떤 이유에서 만드셨는지 궁금합니다!

2024-02-27 03:10 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/user/entity/User.java
> +    private SignType signType;
@Enumrated EnumType.STRING 사용하는거 어떻게 생각하시나요??

2024-02-27 03:11 UTC, tkfkdgowksel approved these changes
고생하셨습니다~

2024-02-27 04:35 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/user/entity/User.java
> +    private SignType signType;
아씨 깜빡했다 ㅋㅋㅋㅋㅋ 추가하겠습니다

2024-02-27 04:35 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/profile/entity/Profile.java
프로필 제가 만들었나요??

2024-02-27 04:37 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/profile/entity/Profile.java
엉덩씨가 만들었네요 ㅡㅡ

2024-02-27 04:40 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/profile/entity/Profile.java
아 삭제가 안되어있고 수정되어있길래요. 알겠습니다 지우는걸 깜빡했었네요

2024-02-27 09:44 UTC, lalabulla requested changes
전체적으로 꼼꼼하게 잘 작성해주신거 같습니다!! 수고하셨습니다👍🏻

2024-02-27 09:44 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/file/entity/File.java
> +    private String fileSize;
파일 타입(jpg, png 등) 저장 유무 여쭤봅니당

2024-02-27 09:44 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/file/entity/File.java
>      private String key;
키도 nullable=false 설정 필요할 것 같습니다!

2024-02-27 09:44 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/user/entity/User.java
> +        USUAL,
USUAL 도 좋은데 다른 네이밍이 좀 더 잘 와닿을 것 같습니다!

2024-02-27 09:44 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/file/entity/File.java
> +    //    private String key;  //  key는 예약어 변경 필요
uploadKey 어떨까요?.? (아니면  fileKey)

2024-02-27 09:44 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/file/entity/File.java
> -    @Column(nullable = false)
엇 빈칸불가 다시 지우신 이유가 있을까요?.?

2024-02-27 23:17 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/file/entity/File.java
> +    //    private String key;  //  key는 예약어 변경 필요
fileKey로 우선 가볼게여

2024-02-27 23:17 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/file/entity/File.java
> -    @Column(nullable = false)
이유 없습니다 다시 추가하겠습니다 ㅎㅎ

2024-02-27 23:20 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/user/entity/User.java
> +        USUAL,
GENERAL? NORMAL?
일반 로그인 네이밍 우선 NORMAL로 해놓을게요 회의때 수정 또 하시죠

2024-02-28 02:28 UTC, lalabulla approved these changes

2024-02-28 06:02 UTC, merged