FEAT : 댓글 CRUD 구현
For-MZ/formz-be pull request #16
Opened 2024-03-04 10:15 UTC by lalabulla

## Key Changes 🔑

- 댓글 작성
- 댓글 조회
- 댓글 수정
- 댓글 삭제
- 최종 응답 포맷 구현
- 에러 응답 포맷 구현
- 예외 처리 (전체 포함)

## To Reviewers 🙌🏻

1. 댓글 조회의 경우 현재 페이징 처리를 했지만 조금 지저분해서 리팩토링이 더 필요할 것 같습니다!
2. 맵퍼를 사용해 봤는데 아직까지 조금 불편한게 있는것 같습니다 (정확히 딱 맞아떨어지지 않아서,,)
3. 테스트는 아직 못해서 되는대로 커밋하겠습니다!
4. 자체 코드를 만들어서 처리하기로 했는데 작성하다보니 예외의 경우는 HttpStatus 도 반환은 해줘야할 것 같아서 일단 추가했습니다.
5. 양이 좀 많긴한데 천천히 보시고 코드리뷰 부탁드립니다!

## PR Checklist ✔️

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

## PR 타입 👏🏻

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 문서 업데이트
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

2024-03-05 07:19 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/comment/entity/Comment.java
>  public class Comment extends BaseEntity {
Comment 특성 때문에 접근제어자를 Protected로 사용하신건가요?? 사용하신 의도가 궁금합니다!

2024-03-05 07:31 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/comment/entity/Comment.java
> +    }
if문으로 혹시 모를 중복 검사를 하는 것도 좋을 것 같다고 생각이 듭니다!

2024-03-05 07:36 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/comment/mapper/CommentMapper.java
Mapper 사용 잘하신 것 같네요!! 인자가 여러 개 넘어가는 건 저도 처음 봐서 테스트도 한번 해보면 좋을 것 같네요!

2024-03-05 07:41 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/comment/service/CommentServiceImpl.java
> +}
실제 Repo에서 삭제보단 soft delete가 저희가 정한 방식인 것 같아서,
Status 값만 바꿔 놓는게 더 좋을 것 같습니다!

2024-03-05 07:54 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/comment/service/CommentServiceImpl.java
> +                    int cmtLikeCnt = comment.getCommentLikes().size();
혹시 CommentLike를 가져오실 때 Comment를 작성한 User를 넣는 이유가 궁금합니다!
CommentLike가 어떤 Comment에 대해, 누가 Like를 눌렀는지, Comment와 User 두개를 가지고 있는 것으로 아는데, 그렇다면 Comment로만 선별해서 가져와야 해당하는 Comment의 모든 좋아요를 가져올 것으로 생각해
그것이 의도에 맞지 않나 생각해봅니다!

2024-03-05 07:56 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/exception/PostException.java
Post exception 파트도 작성해주셨군요! 형식 그대로 이어서 사용하도록 하겠습니다

2024-03-05 07:59 UTC, tkfkdgowksel requested changes
전체적으로 꼼꼼하게 잘 작성해주신 것 같습니다.
고생하셨습니다!

2024-03-05 10:22 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/comment/service/CommentServiceImpl.java
> +}
소프트 딜리트로 가시죠~

2024-03-05 12:30 UTC, pis03133 approved these changes

2024-03-05 12:30 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/comment/controller/CommentController.java
> +
저희 나중에 댓글도 정렬 기능 (최신순, 추천순 등) 생길 수 있으니 @PathVariable 보단 @RequestParam 이었나 그게 어떠신지요.. @PathVariable로도 구현 가능하다면 미리 죄송함다

2024-03-05 12:30 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/comment/entity/Comment.java
>  public class Comment extends BaseEntity {
LAZY 로딩써서 프록시 접근할려면 생성자를 Protected로 해줘야되는군요..
JPA 역시 깊은 공부가 필요합니다... 공식문서 보긴 귀찮아서 전 구글링했슴다
관련 링크 : 
https://velog.io/@kevin_/%EB%82%B4%EA%B0%80-NoargsConstructor-access-AccessLevel.PROTECTED%EB%A5%BC-%EC%99%9C-%EC%9E%91%EC%84%B1%ED%96%88%EC%9D%84%EA%B9%8C

2024-03-05 12:30 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/comment/exception/CommentExceptionList.java
> +}
알파벳 2개 + 숫자2개(?)로 수정하기로 했었죠??

2024-03-05 12:30 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/comment/mapper/CommentMapper.java
> +    ChildCommentRes toChildCommentRes(boolean cmtLiked, int cmtLikeCnt, Comment comment);
오 복잡한데요 뭐지

2024-03-05 14:51 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/entity/Comment.java
>  public class Comment extends BaseEntity {
인서님이 말씀하신 이유도 있지만, 댓글 엔티티를 생성하는 경우 무조건 연관관계도 동시에 이루어지도록 생성자를 만들었어요! 그래서 기본 생성자의 경우는 Protected로 막아놓았습니다!

2024-03-05 14:52 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/entity/Comment.java
> +    }
어떤 중복검사를 말씀하시는 걸까요?.?

2024-03-05 14:54 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/mapper/CommentMapper.java
저는 이왕 맵퍼를 사용하는 김에 DTO에 맵핑되는 좋아요 유무, 좋아요 수, 대댓글리스트 또한 한꺼번에 담고 싶었는데, 이부분은 지금 보면 서비스단에서 추가로 맵핑이 이루어지고 있어서 그렇게 느꼈습니다! (커스텀하는 부분이나 추가적으로 더 MapStruct를 공부해봐야 할 것 같아요!)

2024-03-05 14:55 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/service/CommentServiceImpl.java
> +}
앗 맞네요 무지성 CRUD 하다보니,,ㅎㅎ 수정해서 반영하겠습니다! 인서님 말씀처럼 응용시켜도 좋을 것 같아요!!

2024-03-05 15:01 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/service/CommentServiceImpl.java
> +                    int cmtLikeCnt = comment.getCommentLikes().size();
음 56번째 줄의 CommentLike의 경우는 특정 댓글 + 특정 유저의 좋아요 유무입니다! 어떤 User가 누른 댓글은 여러개일 테니 유일성을 위해선 User + Comment로 조회해야 합니다! 성영님이 말씀하신 건 좋아요 갯수인 것 같은데요(모든 좋아요들). 이부분은 60번째 줄에서 comment의 연관관계인 좋아요들을 가져와 크기를 담고 있습니다 (전체 좋아요 수)

2024-03-05 15:01 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/exception/PostException.java
감사합니다 :)

2024-03-05 15:04 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/controller/CommentController.java
> +
앗 그부분은 고려해보지 못했네요! 지금 생각으론 두가지 모두를 사용할 수 있을 것 같은데 한 번 알아보고 반영해보도록 하겠습니당

2024-03-05 15:04 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/exception/CommentExceptionList.java
> +}
넵!

2024-03-05 15:04 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/mapper/CommentMapper.java
> +    ChildCommentRes toChildCommentRes(boolean cmtLiked, int cmtLikeCnt, Comment comment);
맵핑이 쉬운 듯 어렵더라구요(오열)

2024-03-05 15:05 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/comment/entity/Comment.java
> +    }
User와 Post에 있는 리스트에 현재 Comment가 이미 포함되었는지 중복 검사 말씀드린거였습니다!
보통의 경우에는 setUserAndPost가 필요에 의할 때만 동작하겠지만
혹시 모르게 중복으로 추가로 들어가게 되는 경우가 있을까 해서 였습니다!

2024-03-05 15:26 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/comment/service/CommentServiceImpl.java
> +                    int cmtLikeCnt = comment.getCommentLikes().size();
아하 cmtLiked에 의미를 잘 몰랐던 것 같습니당
생각해보니 좋아요 수만 확인하면 되니 60번째 줄로 해결이 되는군요. 확인입니다!!

2024-03-05 15:28 UTC, tkfkdgowksel approved these changes

2024-03-06 02:42 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/comment/entity/Comment.java
> +    }
setUserAndPost 메소드가 private이고, Comment를 생성할때만 호출되기 때문에 지금 생각으론 중복여지가 없어보이긴 해요! 추후 좀 더 개발이 이루어지면 성영님 말씀 고려해서 구현해보도록 하겠습니다!!🙃

2024-03-06 03:24 UTC, merged