Feat : Post CRUD 1차 구현
For-MZ/formz-be pull request #18
Opened 2024-03-07 15:27 UTC by tkfkdgowksel

## Key Changes 🔑

1. Post CRUD 기본 구현 (추가 작업 필요)
2. Post Exception 추가
3. Post Mapper 구현, Comment Mapper 수정
4. Entity간 연관 관계 연결

## To Reviewers 🙌🏻

모두에게 불편한 Mapper를 사용하지 말자고 오늘 말씀해주셨지만
일단 작업 중이던 것이 있어 Mapper를 이용해서 작업해보았습니다.
추가적으로 UserMapper 등 구현 할 때,
너무 어려움을 느끼게 되면 사용하지 않아도 좋을 것 같습니다.

토큰을 활용해 현재 유저의 ID 값을 불러오는 메서드가 있었으면 좋겠고,
(꼭 토큰을 활용하지 않더라도 현재 사용자를 식별해낼 필요가 있다고 느꼈습니다.)

추가적으로 저는 로컬 실행 시 오류로 인해서 임시적으로 규현님이 작성해주신 부분 중 commentRepository 부분을 주석 처리 해놨고 이를 사용하는 Service 부분도 일부 수정하였습니다. 
한번 확인해주시면 감사하겠습니다~

빠른 다음 작업을 위해 일단 빠르게 PR을 올리는 것이라
아직 허술한 점이 많을 것으로 예상되지만
꼼꼼하게 리뷰해주시면 정말 감사하겠습니다 :)

## PR Checklist ✔️

- [x ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

## PR 타입 👏🏻

- [x ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 문서 업데이트
- [x ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

2024-03-07 17:09 UTC, lalabulla requested changes
전체적으로 잘 작성해주셨습니다! 몇가지 필요한 것들을 적어보자면,
- 개인적으로 객체/DTO 맵핑의 경우 비지니스단(서비스단) 에서 처리하는 게 어떨까 하는데 인서님과 성영님의 의견이 궁금합니다!
- 맵퍼의 관해서는 저도 잘 모르기 때문에 리뷰를 달지 않았습니다ㅜ

정도 인 것 같습니다! 양이 많아 저도 놓친 부분이 있을지도 모르겠습니다🥲 수고하셨습니다!!

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Content.java
> +    private String imageUrl;
개인적으로 임베디드 타입의 경우 필수적으로 들어가는 것만 쓰는 게 어떨까 합니다! 이미지 URL의 경우는 있는 게시글도 있지만 없는 게시글도 존재하니까요. 그리고 임베디드 타입으로 빼신 이유가 있을까요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/category/entity/Category.java
> +        POLICY, HOUSE, EMPLOYMENT, FOUNDED, FREEDOM, HONEYTIP;
카테고리의 한글 설명도 필요해 보입니다! 그리고 CategoryCode -> Category로 바꾸기로 했던거 같아서 수정해주시면 감사하겠습니다!

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Post.java
> +@Setter
엔티티에는 @Setter를 추가하지 않는 것이 좋습니다! 사용을 지양해주세요🥲

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostReq.java
> +    private CategoryCode category;
enum 자체를 받는 것이 아닌 String 으로 받아 서버에서 변환해주지 않아도 괜찮나요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostReq.java
> +    private Content content;
String 이 아닌 Content 객체를 받는 이유가 있으신가요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostReq.java
> +    @NotNull
@NotNull 보단 NotBlank 가 어떨까요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostRes.java
> +    private int postId;
Long 이 아닌 int로 하신 이유가 있을까요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +@Validated
어떤 부분 검증을 위해 사용하신건가요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/global/entity/BaseEntity.java
> +@Setter
엔티티에 @Setter는 지양해주세요!

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/category/entity/Category.java
> +@Setter
@Setter 사용을 지양해주세요🥲

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostRes.java
> +@Setter
DTO는 Setter 사용을 지양하는 것은 아니지만, 괜찮다면 생성자로 필드값을 다루는게 좋을 것 같습니다! :)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Post.java
> +    public void beWatched(){
메소드 명 수정이 필요해보입니다 :) (viewPlus 라던지 등등)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostRes.java
> +    private Content content;
Content 객체 자체를 보내기 보단, String 으로 가공하여 주는 것이 좋은 방향인 것 같습니다 :)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostRes.java
> +    private Category category;
이부분 또한 객체보단 이름(String)을 보내는 것이 좋아보입니다 :)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +        return liked;
liked 변수를 두지 않고 true / false 자체를 반환하는 것도 괜찮을 것 같습니다 :)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +        return bookmarked;
bookmarked 변수를 두지 않고 true / false 자체를 반환하는 것도 괜찮을 것 같습니다 :)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +        editField(modPost::getContent, post::setContent);
수정의 경우 엔티티 필드값의 변환이기 때문에 엔티티 클래스 안에 메소드를 만드는 것이 좋아 보입니다! 추가로 게시글 생성 DTO와 게시글 수정 DTO는 구별하여 생성해주시면 감사하겠습니다

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +    public PostRes convertPostRes(Post post){
해당 메소드를 게시글 조회 메소드에서 따로 빼신 이유가 있나요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/exception/PostExceptionList.java
> +    UNAUTHORIZED_POST_ACCESS("PO02", HttpStatus.UNAUTHORIZED, "허용되지 않은 접근입니다.");
에러 메시지를 조금 더 상세하게 적어주면 좋을 것 같습니다 (ex. 게시물 접근 권한이 없습니다.)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/mapper/PostMapper.java
> +    @Mapping(source = "likeCnt", target = "likeCnt")
필드명이 동일한 경우에는 생략해도 좋을 것 같습니다 :)

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +        return new ResponseEntity(ResponseDto.create(201, CREATE_POST_SUCCESS.getMessage(), response), HttpStatus.CREATED);
ResponseEntity.status().body() 문법을 사용하면 가독성이 더 좋아 질 것 같습니다! 그리고 코드의 경우 직접 입력보단, httpstatus.value() 로 전달하는 게 좋을 것 같아요! 추가로 반환값이 ResponseDto를 포함하고 있는 구조여서 반환 타입은 ResponseEntity<ResponseDto\<PostRes\>> 가 적절한 것 같습니다!

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +    public ResponseEntity checkPostList(@RequestParam(name = "page", defaultValue = "1", required = false) int page,
check 보단 get 네이밍이 더 적절해 보입니다! 그리고 페이지 사이즈를 저희가 변환할 수 있나요?.?

2024-03-07 17:09 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/exception/InvalidSortParamException.java
> +        super(POST_NOT_FOUND.getStatusCode(), POST_NOT_FOUND.getHttpStatus(), POST_NOT_FOUND.getMessage());
POST_NOT_FOUND로 잘못 적으신 것 같아요!ㅜㅜ

2024-03-08 01:14 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Content.java
> +    private String imageUrl;
![Post Create Dto](https://github.com/For-MZ/formz-be/assets/19697063/6d555873-855e-4995-b69a-9f2592fc81ba)

2024-03-08 01:17 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Content.java
> +    private String imageUrl;
API 명세서 중 게시글 작성 RequestBody 부분입니다!
저 부분을 표현하려 방법을 잘 찾던 중 발견한 것이 임베디드 타입이었는데
지금 와서 생각해보니 임베디드 타입으로 저렇게 포함시키는 형태가 되는지 모르겠네용

2024-03-08 01:18 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Post.java
> +@Setter
Mapstruct가 Runtime에 Impl을 구현할 때 데이터 접근을 위해 Setter를 사용한다 하더라구요 ㅜㅜ
Setter를 사용하지 않고 mapstruct의 객체 접근을 허용해줄 수 있는 방법을 찾아보겠습니다!

2024-03-08 01:21 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostReq.java
> +    private CategoryCode category;
이것도 아마 Mapstruct를 바로 사용하려고 타입을 맞추기 위해 이렇게 작성했던 것인데
String으로 받아서 저희가 변환하고 예외처리 하는 것도 좋아보입니다!

2024-03-08 01:23 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostReq.java
> +    private Content content;
이것도 위와 같은 이유입니다!
근데 이것은 제가 방법을 찾던 중 임베디드 타입을 다루는 것이 어려워서 일단킵 해둔 것이었는데
제 생각에는 임베디드 타입을 없애는 것이 더 나아보이네용 T.T

2024-03-08 01:27 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostReq.java
> +    @NotNull
엇 NotBlank가 좋아보이네요! 공백을 허용해서 받을 이유가 없을 것 같네요
좋은 지적 감사합니다 ㅎㅎ

2024-03-08 01:28 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostRes.java
> +    private int postId;
이것은 완전 실수군요.. 수정해놓겠습니다 ㅜㅜ

2024-03-08 01:33 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +@Validated
로깅과 검증을 위해서 Controller 작성 시작 시에 전부 붙여뒀던터라
사용하게 되면 그 때 애너테이션을 붙이면 되는데 너무 미리 붙여놓았네요..
사실 어제 애너테이션들 확인하던 중 CORS 에러를 예방하기 위해
@CrossOrigin(origins = "*") 를 Controller 구현 시작 때 붙여놨었는데,
나중에 문제 생기면 그 때 붙여야지 하고 제거해버렸거든요.
일단은 사용하지 않는 해당 애너테이션들 제거해놓겠습니다!

2024-03-08 01:38 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/global/entity/BaseEntity.java
> +@Setter
이것도 Mapper 때문이었는데
엔티티에는 Setter 사용을 자제하는 게 맞는데 제가 깜빡했네요..
클래스 메서드를 사용하거나 Builder를 사용하는 쪽,
아니면 더 좋은 방법이 있다면 그쪽으로 전부 변경하겠습니다!

2024-03-08 01:40 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Post.java
> +    public void beWatched(){
관찰되다 로 번역했었는데..ㅋㅋㅋㅋㅋㅋㅋ
지금 생각해보면 왜 관찰되다로 번역했는지 모르겠네요.
누군가 지켜봐주면 조회수가 증가되는 것을 머릿 속으로 그려서인지..
직관적으로 조회 수 증가를 뜻하는 viewPlus가 좋아보입니다! 수정해두겠습니다~

2024-03-08 01:41 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/dto/PostRes.java
> +    private Content content;
넵! 임베디드 타입 제거하고 전부 String으로 받게 수정해두겠습니다~

2024-03-08 01:44 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +        return liked;
liked와 bookmarked를 Mapper사용을 위해 전부 따로 받아두는 것으로 작성해두다가
뭔가 중복적으로 작동하는 것 같아서 함수 Extract를 하다보니 그 형태 그대로 남아있어서 그렇네요..
이런 형태면 규현님 말씀대로 변수를 두지 않고 바로 return하면 될 것 같습니다! 수정해두겠습니당

2024-03-08 01:48 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +        editField(modPost::getContent, post::setContent);
매번 수정 구현할 때 뭔가 지저분하고 마음에 안들었었는데
엔티티 클래스 메서드를 이용하면 깔끔하게 되겠네요!
제가 지금 엔티티 클래스 메서드를 하나도 작성해두지 않은 상태라
해당 부분은 TODO로 남겨두고 PR 완료 후에 전부 수정해두겠습니다!
생성 DTO와 수정 DTO는 API 명세 상으로 받는 ReqBody가 같아서 일단은 같이 사용하게 두었는데
나누는 것을 고려해보겠습니다 :)

2024-03-08 01:53 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +    public PostRes convertPostRes(Post post){
조회 메소드를 제외하고도 Res로의 Mapper의 사용이 필요한 부분이 많을 것으로 예상되어 따로 빼내었습니다!

현재 Mapstruct의 입력 인자가 하나인 경우에는 따로 구현해줄 부분이 없는데,
입력 인자가 여러 개가 되다 보니,
(Ex. PostRes postToPostRes(Post post, boolean bookmarked, boolean liked, int likeCnt); )
그것을 처리할 방법을 찾다가 서비스 계층에서 메서드 작성을 해놓은 상태입니다.
현재 상황만 놓고 봐서는 Mapper 사용에 참 많은 불편함이 있는 것 같네요...

2024-03-08 01:54 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/exception/PostExceptionList.java
> +    UNAUTHORIZED_POST_ACCESS("PO02", HttpStatus.UNAUTHORIZED, "허용되지 않은 접근입니다.");
게시물 exception이니까 게시물에 대한 메시지가 들어가야 맞는 것 같네요.
앞으로 에러 메시지 작성할 때 주의하겠습니다! 해당 메시지은 수정해둘게요~

2024-03-08 01:57 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/mapper/PostMapper.java
> +    @Mapping(source = "likeCnt", target = "likeCnt")
source는 입력 인자 변수명이고 target은 Response에 매핑 될 변수명입니다!
일단은 변수명이 생각이 안나서 동일하게 작성해보았는데,
나중에 테스트를 해보고 혹여 필드 명이 같아 정상적으로 작동하지 않는다면 수정해두겠습니다!

2024-03-08 01:58 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/exception/InvalidSortParamException.java
> +        super(POST_NOT_FOUND.getStatusCode(), POST_NOT_FOUND.getHttpStatus(), POST_NOT_FOUND.getMessage());
하하.. 수정해두겠습니다..^^
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-03-08 02:02 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +    public ResponseEntity checkPostList(@RequestParam(name = "page", defaultValue = "1", required = false) int page,
어떠한 생각에 get에서 check로 바꾸었었는데 이유가 잘 생각이 안나네요..
지금 제 생각에도 get 네이밍이 더 적절해 보이네요!
페이지 사이즈는 현재 고정으로 되어있는데
저번에 동욱님이 추후 혹시라도 변경할 일이 있을 수도 있지 않겠냐고 말씀하시면서
API 명세서 상에 optional 파라미터로 남겨두셔서 일단 작성해두었습니다!

2024-03-08 02:12 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +        return new ResponseEntity(ResponseDto.create(201, CREATE_POST_SUCCESS.getMessage(), response), HttpStatus.CREATED);
1. ResponseEntity.status().body() 문법이 상태 값을 먼저 확인할 수 있어서 괜찮은 것 같습니다
2.  httpstatus.value() 이것도 직접적 숫자 입력보단 가독성도 좋고 실수할 일도 없을 것 같아서 좋은 것 같네요 !
3. ResponseEntity<ResponseDto<PostRes>> 제네릭 타입이 따로 명시해주지 않아도 입력 인자에 따라 타입이 자동으로 변환되는 것으로 알고 있어서 편해서 이렇게 사용하고 있었는데, 좀 길더라도 직접적으로 명시해주는 것이 더 좋을까요??

2024-03-08 02:13 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/category/entity/Category.java
> +        POLICY, HOUSE, EMPLOYMENT, FOUNDED, FREEDOM, HONEYTIP;
해당 부분은 PR 완료 후 카테고리 대공사가 필요해보여서.. 나중에 할 일로 두었습니당
그 때 저희가 설계했던 구조라면 enum 타입도 제거해야 할 것 같아서요 ㅜㅜ

2024-03-08 03:19 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +@Validated
엥 지금 보니까 crossorigin도 아직 붙어있네욤 크흠

2024-03-08 03:40 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Post.java
> +@Setter
현재 엔티티 Setter를 제거해도 잘 실행되는 것 같아서 엔티티 Setter는 전부 제거하였습니다!

2024-03-08 08:16 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Content.java
> +    private String imageUrl;
저렇게 응답을 하고 싶다면 content라는 이름의 DTO를 만들어 값을 담는게 좋을 것 같아요! 그리고 게시글 내용와 링크만 묶는 것이 조금 의아하긴 합니다

2024-03-08 08:19 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/entity/Post.java
> +@Setter
요청 DTO를 엔티티로 맵핑 할 때는 빌더 혹은 Setter가 필요하고, 엔티티를 응답DTO로 맵핑시 getter만 필요하다고 합니다 :)

2024-03-08 08:23 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/service/PostServiceImpl.java
> +    public PostRes convertPostRes(Post post){
아하 Mapper 때문이었군요 알겠습니다!!

2024-03-08 08:25 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/mapper/PostMapper.java
> +    @Mapping(source = "likeCnt", target = "likeCnt")
맵핑 시 필드 명이 동일하면 알아서 연결되어 값이 할당되더라구요 (입력 인자여도)🙃

2024-03-08 08:26 UTC, lalabulla commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +        return new ResponseEntity(ResponseDto.create(201, CREATE_POST_SUCCESS.getMessage(), response), HttpStatus.CREATED);
아하 자동 변환되는 군요! 저도 몰랏네용 성영님 따라가겠습니다👍🏻

2024-03-08 08:30 UTC, lalabulla approved these changes

2024-03-08 10:23 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/mapper/PostMapper.java
> +    @Mapping(source = "likeCnt", target = "likeCnt")
아하 이건 또 몰랐었네요 아주 좋은 기능인 것 같습니다!
그렇다면 중복되므로 제거하겠습니다😁

2024-03-08 23:00 UTC, pis03133 requested changes

2024-03-08 23:00 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/category/entity/Category.java
>      private CategoryCode categoryCode;
enum을 안 쓰기로 한건가요?? 
enum 쓰면서 테스트 코드로 카테고리 삽입하는 코드 짜놓는거 아니었나요! 
Entity는 enum으로 관리하고,
Response, Request만 String으로 받아 관리하자는 규현님의 말씀을 잘 못 이해하신게 아닌지..?

2024-03-08 23:00 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/comment/service/CommentServiceImpl.java
> +        List<Comment> childComments = commentRepository.findAll(pageable).getContent(); // repository 에러 발생 후 수정되었음
주석 지워도 될거 같습니다 ㅎㅎ

2024-03-08 23:00 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +        Post post = postService.createPost(mapper.postReqToPost(postReq));
postService.createPost가 POST 객체를 return하고 있는듯 한데..
리턴값 꼭 줘야되나요?! 이유가 알고 싶습니다. (진짜 모름.)

2024-03-08 23:00 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(ResponseDto.create(HttpStatus.CREATED.value(), CREATE_POST_SUCCESS.getMessage(), res));
return 해주는 response 부분 규현님 작성하신대로 통일하시는게 안 나을까요?? 
EX.) ResponseEntity.ok(ResponseDto.create(CREATED.value(), CREATE_POST_SUCCESS.getMessage());
그리고 게시글 생성인데 post 같이 보내주는 이유가 있나요 ?? (바로 위 댓글이랑 동일한 궁금점임)

2024-03-08 23:00 UTC, pis03133 commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +
@RequestParam으로 받는 부분 좀 지저분한데.. Class 하나 따로 만들어서 받는게 어떨까요??
건의만 드려봅니다

2024-03-08 23:00 UTC, pis03133 approved these changes

2024-03-09 00:39 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +        Post post = postService.createPost(mapper.postReqToPost(postReq));
처음에는 API 명세서 상 Res에 PostId를 반환하는 부분을 위해 create에 대한 객체를 반환하고
거기서 Id을 가져와 Res를 작성하려했었는데
그게 어느 순간 객체를 반환하고 있었네요
인서님 말씀대로 애초에 Service에서도 객체를 반환 시킬 이유가 없어보여서 수정을 하겠습니다
앞으로 create에 대한 객체 리턴은 필요 없어 보이는군요

2024-03-09 00:43 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(ResponseDto.create(HttpStatus.CREATED.value(), CREATE_POST_SUCCESS.getMessage(), res));
1. 일단 제가 경험해본 바로는 Response.ok 에 해당하는 방식 중 없는 Status가 많더라고요
Ex) HttpStatus.UNAUTHORIZED -> ResponseEntity.unauthorized 없음
2. 규현님이 위 양식( ResponseEntity.status().body() )을 제안하셔서 저렇게 수정을 해놓은 것입니다
3. create에 대한 객체는 보내지 않는 것으로 수정해놓겠읍니당

2024-03-09 00:45 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/post/controller/PostController.java
> +
동욱님이랑 같이 API 명세서 작성하면서
저 부분에 대해서 param으로 받는게 나을지 req로 받는게 나을지 엄청 고민하다가
일단은 param으로 받기로 해둔 상태라 param으로 결정했었는데
param 자체가 지저분하다 생각이 들면 그냥 req를 이용하는 것도 방법일 것 같습니다

2024-03-09 00:51 UTC, tkfkdgowksel commented on Server/src/main/java/ForMZ/Server/domain/category/entity/Category.java
>      private CategoryCode categoryCode;
제가 부트캠프에서 해당 방법을 배웠던 강사님 Repository solution 코드를 확인해보니
메뉴 이름을 String으로 관리하는 것을 봤어서 String으로 관리하려 했던 것과,
카테고리 명을 굳이 enum 방식으로 관리를 해야할까 라는 생각이 들었어서 String으로 관리하려 했었습니다.
하지만 저희가 직접적으로 카테고리 명을 가지고 데이터들을 다룰 것이라면 enum 형식으로 관리하는게 더 편리할 것 같긴하네요. 그렇다면 일단 enum 방식으로 사용을 하겠습니다

2024-03-09 00:53 UTC, merged