Feat/mod package
For-MZ/formz-be pull request #7
Opened 2024-01-30 14:06 UTC by tkfkdgowksel

## Key Changes 🔑

- 패키지 네이밍 수정
[^1]  api -> controller
[^2]  application -> service
[^3] domain -> entity
[^4] dao -> repository

- 도메인 패키지 내의 도메인 추가
( alarm, category, comment, file, information, like, profile, searchWord)

## To Reviewers 🙌🏻

ERD 상의 추가되었던 테이블들은 추후 필요에 따라 삭제하거나 추가해주시면 될 것 같습니다.
내부 코드 최소 구현을 다 마치고 PR 올리려다 혹시 빠르게 구현을 원하실 분 계실까 하여 지금 올립니다.

## PR Checklist ✔️

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

## PR 타입 👏🏻

- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 문서 업데이트
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

2024-01-30 15:23 UTC, lalabulla requested changes
좋아요(like)는 post 안에 컬럼으로 포함하는건 어떤가요?.?
두 분 의견 궁금합니다!

2024-01-30 15:30 UTC, tkfkdgowksel commented
게시판 ERD 다이어그램들을 좀 찾아봤는데여,
단순 좋아요 카운팅만 중요하다면 컬럼에 추가되면 좋을 것 같은데,
그것이 아닌 좋아요를 누른 유저 자신만이 자신의 좋아요를 취소할 수 있게 해야 하는 것 같아서
유저 테이블과 연결을 위해 좋아요 테이블을 따로 빼놓는 것 같더라구요!
comment_like 와 post_like 두 테이블을 따로 빼는 걸 보통 추천해주시던데
일단은 상세한 부분은 따로 상의해보려고 추가/삭제 가능하게 위에서 임시로 like 테이블 만들어둔거였습니다!

2024-01-30 15:35 UTC, tkfkdgowksel commented
혹시 post 컬럼에 포함시키면서 위 부분들을 해결 가능하다면,
저는 포함시키는 것 찬성입니다~ :D

2024-01-31 06:16 UTC, pis03133 commented
@lalabulla @tkfkdgowksel 
저도 성영님 의견에 동의합니다
좋아요 테이블 따로 빼두고 쓰는게 좋아보여용

2024-01-31 07:59 UTC, lalabulla commented
> 게시판 ERD 다이어그램들을 좀 찾아봤는데여, 단순 좋아요 카운팅만 중요하다면 컬럼에 추가되면 좋을 것 같은데, 그것이 아닌 좋아요를 누른 유저 자신만이 자신의 좋아요를 취소할 수 있게 해야 하는 것 같아서 유저 테이블과 연결을 위해 좋아요 테이블을 따로 빼놓는 것 같더라구요! comment_like 와 post_like 두 테이블을 따로 빼는 걸 보통 추천해주시던데 일단은 상세한 부분은 따로 상의해보려고 추가/삭제 가능하게 위에서 임시로 like 테이블 만들어둔거였습니다!

아하 좋아요! 따로 빼는 걸로 하겠습니당

2024-01-31 08:01 UTC, lalabulla approved these changes

2024-01-31 08:01 UTC, merged